### ISSUE TITLE
Should Availability Zone be a conditional field for all providers that support an availability zone concept (today it's optional)

### ISSUE THREAD

**Issue by ahullah** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#367] opened 2024-03-22 15:54 UTC
### Description
Should Availability Zone be a mandatory field for all providers that support an availability zone concept

### Proposed approach
Where a provider supports placing resources in a specific availability zone this detail should be included

### Github issue or Reference
Follows up from issues discussed in PR #331 

### Specific text proposed to be included:
The AvailabilityZone column MUST be present in the billing data when the provider supports deploying resources or services within an availability zone. This column MUST be of type String and MAY contain null values when a charge is not specific to an availability zone.

**Comment by ahullah** [comment] 2024-03-22 15:56
context from PR:
[flanakin](https://github.com/flanakin) reviewed [last week](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/331#pullrequestreview-1937480477)
[specification/columns/availabilityzone.md](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/pull/331/files/586c58ec22d2aafe38381164ad77a64aaf7d2e9f#diff-25f83c6f39b9b4718a4350eb64858cc9c5eff0229d6dba225ea04323147cc947)

The AvailabilityZone column SHOULD be present in the billing data. This column MUST be of type String and MAY contain null values.
The AvailabilityZone column MUST be present in the billing data when the provider supports deploying resources or services within an *availability zone*. This column MUST be of type String and MAY contain null values when a charge is not specific to an *availability zone*.
Member
@[flanakin](https://github.com/flanakin) flanakin last week
nit: Do we want to say MUST NOT or SHOULD NOT be present when the provider does not support AZs? I'm fine without it. Just thinking out loud since we talked about this.

Member
Author
@[udam-f2](https://github.com/udam-f2) udam-f2 3 days ago
In that case, we have to describe this scenario of when to include and when to exclude in every column which seems unnecessary to me. I don't see an issue if a provider provides a nullable FOCUS column with nulls when it doesn't apply to them. For that reason, I'm ok without but if others feel it's needed, we can go an update all columns to specify the exclusion case. Thoughts?

Member
@[marc-perreaut](https://github.com/marc-perreaut) marc-perreaut 2 days ago • 
From my practitioner perspective, I would find unclear that a column is present but always populated with null values, because the provider does not support it. Indeed, I could not differentiate the case where a value is null because the provider does not support the column and the case where the provider supports the column but it's the case where the value is null. If a column is present, I would expect the provider supports it and provides non-null values in the relevant cases.

Meanwhile, specifying the exclusion cases for every column might be heavy. Maybe this could be specified in the nullable attribute? If a column is nullable, then null values must not be used if the provider does not support the column: in that case, the column must be made absent.

Member
@[flanakin](https://github.com/flanakin) flanakin yesterday
Marc's reaction is the same thing we discussed in the maintainer meeting. @rileyjenk was saying the same thing...

There's a semantic difference between a column not being in the dataset and being null. If a column is not in the dataset, then it means it's not applicable (or maybe not available) for that provider. If the column is null, then that means it's applicable but does not have a value for that specific charge.

To use a real example, Microsoft supports AZs but it's not in the cots data. If our FOCUS dataset includes an AvailabilityZone column, we're implying that you can expect to get your AZ value in the cost data. But the column will always be null, which doesn't match practitioners' expectations, as Marc called out, and "breaks" any reports that rely on AZ.

We could have an attribute to define this but I personally would rather see it in each applicable column. It doesn't need to be on all of them. In all that I ran thru in this PR, there were only a few.

Again, I'm okay either way but it seems the "only include supported columns" logic is sound and helps practitioners. If the only downside is we have a few more sentences to be explicit, I would argue it's worth it. Are there other downsides? Either way, I'm happy to go with what others think. Just wanted to bring it up as it was brought up as being useful.

Member
Author
@[udam-f2](https://github.com/udam-f2) udam-f2 yesterday
Totally aligned on the dataset-level presence of a column vs row-level nullability of the column.

At the end of the day, once the datasets are combined as it's the promise of FOCUS, you're always looking at the union of columns. So while in a single provider-level dataset you might be able to quickly guess if a provider might be supporting a concept/column or not, you can't easily do that once you're looking at the higher-level integrated dataset. Many providers are also now supporting creating custom projections so I'd argue the presence of a column can't always be counted on because you might only export a subset.

If you all are still aligned, I'm happy to add or you can suggest an update in the nullability attribute OR possibly in section 2 related to compliance.

Member
@[flanakin](https://github.com/flanakin) flanakin 19 hours ago
I had that thought as well... Multi-cloud or multi-dataset is still a smaller subset of overall practitioners who will use FOCUS. I see the overarching value of FOCUS being clearer expectations for practitioners whether they use one or more datasets. With that context, I would lean towards optimizing for the single dataset scenario, noting that it's irrelevant when merged with other datasets that have different levels of support.

But again, I'm looking for others to chime in. This is probably a good, quick survey we can knock out in one of the meetings.

Member
@[marc-perreaut](https://github.com/marc-perreaut) marc-perreaut 7 hours ago • 
Indeed, the merge of FOCUS datasets raises questions.

The specification says:

The value [of PricingUnit] MUST NOT be null if SkuPriceId is not null and MUST be null if SkuPriceId is null.

After the merge, if absent columns are handled with null values, this statement is not true for the charges (rows) of providers that do not support SkuPriceId. Another option for the merge is for a practitioner to put special values for missing columns, for example "<not supported>". Maybe there are other options.

It would be interesting to get others' view in a meeting.

Member
Author
@[udam-f2](https://github.com/udam-f2) udam-f2 6 minutes ago
The group decided that we make the normative prose about the presence of the data in the charge record. In this case, the group decided that it should remain a SHOULD to prevent providers from going out of compliance for not providing AZ. Column presence is defined in the schema section.

**Comment by ahullah** [comment] 2024-04-09 15:40
We are going to close this PR following discussion on 9/4/24 and revisit this post v1 GA with the expectation that AZ will become a MUST column for all providers that support the concept post v1 GA

**Comment by ahullah** [comment] 2024-04-09 15:40
we will keep this discussion open for post v1 GA review

**Comment by jpradocueva** [comment] 2024-04-10 15:28
@ahullah, Alex, the issue is linked to milestone v1.x. This means that it is not listed in our current workload. Do you want to be visible as part of v1.0?

**Comment by ahullah** [comment] 2024-04-10 16:00
@jpradocueva yes I think we resolved yesterday to move this to post v1.0... thanks

**Comment by ahullah** [comment] 2024-04-10 16:00
We need to canvas more community feedback

**Comment by jpradocueva** [comment] 2024-04-12 04:41
This issue is closed as the associated PR #369 was closed.
The group agreed to merge #394, where ChargeFrequency is RECOMMENDED.

**Closed** 2024-04-12 04:41 UTC
Labels: discussion topic
