### ISSUE TITLE
Review the PricingQuantity metric

### ISSUE THREAD

**Issue by ijurica** [FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec#293] opened 2024-01-22 20:14 UTC
### Type
> Type of issue: Metric

### Description

Current definition of the Pricing Quantity:
> The Pricing Quantity represents the volume of a given resource or service used or purchased based on the [Pricing Unit](https://github.com/FinOps-Open-Cost-and-Usage-Spec/FOCUS_Spec/blob/working_draft/specification/columns/pricingquantity.md#pricingunit)...

**QUESTION:**  
Does Pricing Quantity represent **...the volume of a given resource or service...** or **...the volume of a given SKU associated with a resource or service...**? 

**SUGGESTION:**
Consider rephrasing current Pricing Quantity definition and description.

_NOTE: Applies to Usage Quantity as well_

**Comment by flanakin** [comment] 2024-01-23 09:34
Nice catch!

Should we merge this with the same change for UsageQuantity (#294)? Seems they're both bound to SKU.

**Comment by mike-finopsorg** [comment] 2024-01-24 18:34
Related to #294

**Comment by ijurica** [comment] 2024-02-13 15:41
For further discussions/progress on this issue:

- For definition and nullability updates check out the corresponding PR #324.
- For clarification on PricingUnit vs UsageUnit and block-pricing, including sample data refer to the additional Discussion topic/Proposal #327.

**Comment by udam-f2** [comment] 2024-02-26 19:46
Duplicate of #294 
Both concerns were addressed in the same PR

**Closed by udam-f2** 2024-02-26 19:46 UTC
Labels: spec change
